version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: youtube_postgres_db
    environment:
      POSTGRES_USER: dbt_user
      POSTGRES_PASSWORD: dbt_password
      POSTGRES_DB: youtube_raw_db
    ports:
      - "5432:5432" # Ánh xạ cổng 5432 của máy bạn vào 5432 của container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: